import "./global.scss";
import type { Metadata } from "next";
import localFont from "next/font/local";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// Font files can be colocated inside of `pages`
const myFont = localFont({
  src: "../../public/fonts/iran-sans/IRANSans-Medium-web.woff",
});

export const metadata: Metadata = {
  title: "SHB Architecture",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body style={myFont.style}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
